name: build and dockerfile-compose


on:
  push:
    branches: 
      - main

jobs:
  build-and-dockerfile-compose:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: Docker build and push 
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
          docker build -t raphaelsiston/dockerfile-compose:latest .
          docker push raphaelsiston/dockerfile-compose:latest
